name: locator
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts 
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^0.16.0
  conditional_wrapper: ^1.0.1
  cupertino_icons: ^1.0.0
  equatable: ^1.2.6
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  font_awesome_flutter: ^8.11.0
  geolocator: ^6.2.0
  get_it: ^5.0.6
  google_fonts: ^1.1.2
  google_maps_flutter: ^1.2.0
  google_sign_in: ^4.5.9
  location: ^3.2.4
  mockito: ^4.1.4
  percent_indicator: ^2.1.9+1
  sprung: ^2.0.1+1

dev_dependencies:
  build_runner: ^1.10.1
  mobx_codegen: ^1.1.2
  flutter_test:
    sdk: flutter

  bloc_test: ^7.1.0
  effective_dart: ^1.3.0
  intl_translation: ^0.17.10+1

flutter:
  uses-material-design: true

  assets:
    - assets/map_dark_mode.json
    - assets/map_light_mode.json
    - assets/images/
    - assets/launcher/logo.png